### ISSUE TITLE
Images not displaying on app  after uploading the photos but they are saving in the home directory folder

### ISSUE THREAD

**Issue by Manju151718** [meet244/PicFolio#5]

**Comment by meet244** [comment]
Once images are uploaded they will be stored in /temp folder of the current user then after processing they will move to /master and /preview folders.
that's the process...
so what's going wrong?

**Comment by Manju151718** [comment]
After uploading the photos nothing visible on homepage of app but when I
look at stats there are already number of photos I uploaded, hope u will
resolve this issue soon
